apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp1
  template:
    metadata:
      labels:
        app: webapp1
    spec:
      containers:
        -
          name: webapp1
          image: raosanthos/kube8s:tagversion
          ports:
          - containerPort: 8080
--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: webapp1
  name: webapp1-svc
spec: 
  ports: 
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector: 
    app: webapp1
  type: LoadBalancer
